(() => {
  const ntp = window.NTP = window.NTP || {};

  ntp.dom = {
    app: document.getElementById("app"),
    menu: document.getElementById("menuScreen"),
    game: document.getElementById("gameScreen"),
    board: document.getElementById("board"),
    versionText: document.getElementById("versionText"),
    playButton: document.getElementById("playButton"),
    configButton: document.getElementById("configButton"),
    configPanel: document.getElementById("configPanel"),
    exitButton: document.getElementById("exitButton"),
    backToMenuButton: document.getElementById("backToMenuButton"),
    coinText: document.getElementById("coinText"),
    livesText: document.getElementById("livesText"),
    waveText: document.getElementById("waveText"),
    sessionTimeText: document.getElementById("sessionTimeText"),
    heartStack: document.getElementById("heartStack"),
    floatingMessage: document.getElementById("floatingMessage"),
    victoryOverlay: document.getElementById("victoryOverlay"),
    victoryTitle: document.getElementById("victoryTitle"),
    victorySummary: document.getElementById("victorySummary"),
    victoryTimeText: document.getElementById("victoryTimeText"),
    victoryWaveText: document.getElementById("victoryWaveText"),
    victoryContinueButton: document.getElementById("victoryContinueButton"),
    victoryRestartButton: document.getElementById("victoryRestartButton"),
    victoryMenuButton: document.getElementById("victoryMenuButton"),
    restartConfirmOverlay: document.getElementById("restartConfirmOverlay"),
    restartConfirmYesButton: document.getElementById("restartConfirmYesButton"),
    restartConfirmNoButton: document.getElementById("restartConfirmNoButton"),
    exitConfirmOverlay: document.getElementById("exitConfirmOverlay"),
    exitConfirmYesButton: document.getElementById("exitConfirmYesButton"),
    exitConfirmNoButton: document.getElementById("exitConfirmNoButton"),
    pauseButton: document.getElementById("pauseButton"),
    speedButton: document.getElementById("speedButton"),
    restartButton: document.getElementById("restartButton"),
    towerShop: document.getElementById("towerShop"),
    customWavesInput: document.getElementById("customWavesInput"),
    bgmToggleButton: document.getElementById("bgmToggleButton"),
    sfxToggleButton: document.getElementById("sfxToggleButton"),
    bgmVolumeInput: document.getElementById("bgmVolumeInput"),
    sfxVolumeInput: document.getElementById("sfxVolumeInput"),
    bgmVolumeText: document.getElementById("bgmVolumeText"),
    sfxVolumeText: document.getElementById("sfxVolumeText")
  };
})();
