(() => {
  const ntp = window.NTP = window.NTP || {};

  ntp.dom = {
    app: document.getElementById("app"),
    menu: document.getElementById("menuScreen"),
    game: document.getElementById("gameScreen"),
    board: document.getElementById("board"),
    versionText: document.getElementById("versionText"),
    playButton: document.getElementById("playButton"),
    configButton: document.getElementById("configButton"),
    configBackButton: document.getElementById("configBackButton"),
    configPanel: document.getElementById("configPanel"),
    difficultyPanel: document.getElementById("difficultyPanel"),
    difficultyBackButton: document.getElementById("difficultyBackButton"),
    startGameButton: document.getElementById("startGameButton"),
    exitButton: document.getElementById("exitButton"),
    backToMenuButton: document.getElementById("backToMenuButton"),
    coinText: document.getElementById("coinText"),
    livesText: document.getElementById("livesText"),
    waveText: document.getElementById("waveText"),
    defeatedText: document.getElementById("defeatedText"),
    sessionTimeText: document.getElementById("sessionTimeText"),
    heartStack: document.getElementById("heartStack"),
    comboCounter: document.getElementById("comboCounter"),
    waveTransition: document.getElementById("waveTransition"),
    floatingMessage: document.getElementById("floatingMessage"),
    cardChoiceOverlay: document.getElementById("cardChoiceOverlay"),
    cardChoiceTitle: document.getElementById("cardChoiceTitle"),
    cardChoiceCards: document.getElementById("cardChoiceCards"),
    cardChoiceResult: document.getElementById("cardChoiceResult"),
    cardChoiceContinueButton: document.getElementById("cardChoiceContinueButton"),
    victoryOverlay: document.getElementById("victoryOverlay"),
    victoryTitle: document.getElementById("victoryTitle"),
    victorySummary: document.getElementById("victorySummary"),
    victoryTimeText: document.getElementById("victoryTimeText"),
    victoryWaveText: document.getElementById("victoryWaveText"),
    victoryDefeatedText: document.getElementById("victoryDefeatedText"),
    victoryContinueButton: document.getElementById("victoryContinueButton"),
    victoryRestartButton: document.getElementById("victoryRestartButton"),
    victoryMenuButton: document.getElementById("victoryMenuButton"),
    restartConfirmOverlay: document.getElementById("restartConfirmOverlay"),
    restartConfirmYesButton: document.getElementById("restartConfirmYesButton"),
    restartConfirmNoButton: document.getElementById("restartConfirmNoButton"),
    exitConfirmOverlay: document.getElementById("exitConfirmOverlay"),
    exitConfirmYesButton: document.getElementById("exitConfirmYesButton"),
    exitConfirmNoButton: document.getElementById("exitConfirmNoButton"),
    towerDeleteConfirmOverlay: document.getElementById("towerDeleteConfirmOverlay"),
    towerDeleteConfirmYesButton: document.getElementById("towerDeleteConfirmYesButton"),
    towerDeleteConfirmNoButton: document.getElementById("towerDeleteConfirmNoButton"),
    undoTowerButton: document.getElementById("undoTowerButton"),
    deleteTowerButton: document.getElementById("deleteTowerButton"),
    pauseButton: document.getElementById("pauseButton"),
    speedButton: document.getElementById("speedButton"),
    restartButton: document.getElementById("restartButton"),
    towerShop: document.getElementById("towerShop"),
    customWavesInput: document.getElementById("customWavesInput"),
    xboxLayoutButton: document.getElementById("xboxLayoutButton"),
    switchLayoutButton: document.getElementById("switchLayoutButton"),
    bgmToggleButton: document.getElementById("bgmToggleButton"),
    sfxToggleButton: document.getElementById("sfxToggleButton"),
    bgmVolumeInput: document.getElementById("bgmVolumeInput"),
    sfxVolumeInput: document.getElementById("sfxVolumeInput"),
    bgmVolumeText: document.getElementById("bgmVolumeText"),
    sfxVolumeText: document.getElementById("sfxVolumeText")
  };
})();
